import io
import sys
import traceback

import matplotlib
matplotlib.use("Agg") #set matplotlib to be not interactive (no pop ups for web environments)
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


def execute_code(code: str, df: pd.DataFrame) -> dict:
    """
    Execute generated pandas code in a restricted scope.

    Returns a dict with keys:
        success (bool)
        text    (str)  — captured stdout
        figure  (Figure | None) — active matplotlib figure, if any
        traceback (str) — only present on failure
    """
    plt.close("all") #Clears all existing figures before each execution, 
                    #preventing leftover charts from a previous run from leaking into the current result.

    stdout_buf = io.StringIO() 
    #Redirects standard output to an in-memory buffer. 
    # So any print(result) inside the generated code gets captured into stdout_buf instead of printing to the terminal. 
    # old_stdout saves the original stdout so it can be restored later.
    old_stdout = sys.stdout
    sys.stdout = stdout_buf

    # Only expose what the generated code should need
    safe_builtins = {
        "print": print,
        "len": len,
        "range": range,
        "enumerate": enumerate,
        "zip": zip,
        "isinstance": isinstance,
        "list": list,
        "dict": dict,
        "str": str,
        "int": int,
        "float": float,
    }

    scope = {
        "__builtins__": safe_builtins, #include nothing in the builtin so that os will not be executed while pandas methods can still be executed
        "df": df.copy(), #copy to prevent wrong mutation of the data
        "pd": pd,
        "plt": plt,
        "sns": sns,
    } # this means that any code generated by the LLM that contains "io", "os", will not be executed
    #this is not necessarily a sandbox, but a measure of security.

    try:
        exec(code, scope)  #execute the code at runtime
        sys.stdout = old_stdout
        output_text = stdout_buf.getvalue().strip()

        figure = plt.gcf() if plt.get_fignums() else None #check if there are any plots generated

        return {
            "success": True,
            "text": output_text,
            "figure": figure,
        }

    except Exception:
        sys.stdout = old_stdout
        tb = traceback.format_exc()
        return {
            "success": False,
            "text": "",
            "figure": None,
            "traceback": tb,
        }